name: AUR

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  aur:
    environment:
      name: aur-update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: AUR update (hyprpanel)
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: hyprpanel
          pkgbuild: ./aur/hyprpanel/PKGBUILD
          updpkgsums: true
          test: true
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_KEY }}
      - name: AUR update (hyprpanel-bin)
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: hyprpanel-bin
          pkgbuild: ./aur/hyprpanel-bin/PKGBUILD
          updpkgsums: true
          test: true
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_KEY }}