name: Release

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.21.5'
          cache: false
      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1.30.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Go generate
        run: go generate ./...
      - name: Check outdated protobuf
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          else
            exit 1
          fi
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
